### PR TITLE
Update the ruby-build plugin before installing

### PR DESCRIPTION
**Pull request by jimmynguyc**

### CODE REVIEW

**Comment by jimmynguyc** [comment]
For issue https://github.com/capistrano-plugins/capistrano-rbenv-install/issues/3

**Comment by bruno-** [comment]
Hi, thanks for opening the PR.

I just realized something, `update_ruby_build` will execute and pull latest ruby build on *every\* deploy! Even if "targeted" ruby is installed.

I propose we run the `update_ruby_build` task *only\* if ruby from `install_ruby` task is about to be installed.

Specific suggestions:
- remove [this line](https://github.com/capistrano-plugins/capistrano-rbenv-install/pull/4/files#diff-883bcd9d658d333ffb01a999afe8e2e8R66)
- place `invoke 'rbenv:update_ruby_build'` before [this line](https://github.com/capistrano-plugins/capistrano-rbenv-install/blob/e1c0bfc51d9d5fba7d71c1fd453a59b5118c7ee1/lib/capistrano/tasks/rbenv_install.rake#L34)

Let me know your thoughts!

**Comment by jimmynguyc** [comment]
Done! Nice catch :)

**Comment by bruno-** [comment]
Great, thanks.
I've merged the updates via the command line. I wanted to squash both commits into one and update the changelog with your contribution. You can check [the commit here](https://github.com/capistrano-plugins/capistrano-rbenv-install/commit/2ee246ccc267aca96cd932bce0c4d64e7af27021).

I've also updated gem version to `1.2.0` and pushed it to rubygems.org.

Closing the PR as the updates are merged.

**Comment by jimmynguyc** [comment]
Thanks! Awesome gem this is.

**Pull request closed without merging**
